#!/bin/bash
echo "Atualizando o Whaticket, por favor aguarde."

#git pull
cd /home/deploy/brunoia/backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
npx sequelize db:seed
cd /home/deploy/brunoia/frontend
npm install
rm -rf build
npm run build
pm2 restart all

echo "Atualização finalizada. Aproveite!"
